name: Build latest OS and EE image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Scan Hazelcast image by Azure (Trivy + Dockle)
        uses: Azure/container-scan@v0
        with:
          image-name: hazelcast/hazelcast:latest
      - name: Scan Hazelcast image by Anchore
        uses: anchore/scan-action@v1
        with:
          image-reference: hazelcast/hazelcast:latest
      - name: Scan Hazelcast Enterprise image by Azure (Trivy + Dockle)
        uses: Azure/container-scan@v0
        with:
          image-name: hazelcast/hazelcast-enterprise:latest
      - name: Scan Hazelcast Enterprise image by Anchore
        uses: anchore/scan-action@v1
        with:
          image-reference: hazelcast/hazelcast-enterprise:latest
