name: Build latest OS and EE image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - run: docker build hazelcast-oss -t leszko/hazelcast:123

      - name: Scan Hazelcast image by Azure (Trivy + Dockle)
        uses: Azure/container-scan@v0
        with:
          image-name: leszko/hazelcast:123
      - name: Scan Hazelcast image by Anchore
        uses: anchore/scan-action@v1
        with:
          image-reference: leszko/hazelcast:123
